/*
 * This file was automatically generated by EvoSuite
 * Sat Nov 15 01:02:50 GMT 2025
 */

package org.apache.commons.cli;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.cli.Converter;
import org.apache.commons.cli.DeprecatedAttributes;
import org.apache.commons.cli.Option;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Option_ESTest extends Option_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test000()  throws Throwable  {
      Option option0 = new Option("n", "");
      option0.setArgs((-1122));
      boolean boolean0 = option0.requiresArg();
      assertEquals((-1122), option0.getArgs());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test001()  throws Throwable  {
      Option option0 = new Option("n", "");
      option0.setArgs((-1122));
      option0.toString();
      assertEquals((-1122), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test002()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder((String) null);
      Option.Builder option_Builder1 = option_Builder0.numberOfArgs(0);
      option_Builder0.longOpt("{G%~N]|;c;Wc#8yM");
      option_Builder1.optionalArg(true);
      Option option0 = option_Builder1.get();
      boolean boolean0 = option0.acceptsArg();
      assertFalse(option0.hasArg());
      assertFalse(option0.hasArgs());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test003()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.valueSeparator('m');
      assertSame(option_Builder0, option_Builder1);
  }

  @Test(timeout = 4000)
  public void test004()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.required(false);
      assertSame(option_Builder0, option_Builder1);
  }

  @Test(timeout = 4000)
  public void test005()  throws Throwable  {
      Option option0 = new Option((String) null, true, "DF-|A(rh]ViC6K\"-K");
      option0.setArgs(122);
      option0.setValueSeparator('-');
      option0.processValue("DF-|A(rh]ViC6K\"-K");
      assertEquals('-', option0.getValueSeparator());
  }

  @Test(timeout = 4000)
  public void test006()  throws Throwable  {
      Option option0 = new Option("0m0EkTx-p", "0m0EkTx-p");
      option0.isValuesEmpty();
      assertEquals((-1), option0.getArgs());
      assertFalse(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test007()  throws Throwable  {
      Option option0 = new Option((String) null, true, "DF-|A8rh]ViC6K\"6K");
      option0.processValue("DF-|A8rh]ViC6K\"6K");
      boolean boolean0 = option0.isValuesEmpty();
      assertFalse(option0.hasValueSeparator());
      assertFalse(boolean0);
      assertFalse(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test008()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.longOpt("6a-vpx.JZV/-K3wf");
      Option.Builder option_Builder1 = option_Builder0.required();
      Option option0 = option_Builder1.get();
      boolean boolean0 = option0.isRequired();
      assertEquals((-1), option0.getArgs());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test009()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null, true, (String) null);
      option0.setOptionalArg(true);
      boolean boolean0 = option0.hasOptionalArg();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test010()  throws Throwable  {
      Option option0 = new Option((String) null, false, "/u%");
      option0.setArgs(157);
      option0.processValue("org.apache.commons.cli.Option");
      option0.getValuesList();
      assertEquals(157, option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test011()  throws Throwable  {
      Option option0 = new Option((String) null, false, (String) null);
      option0.setValueSeparator('4');
      char char0 = option0.getValueSeparator();
      assertEquals('4', char0);
  }

  @Test(timeout = 4000)
  public void test012()  throws Throwable  {
      Option option0 = new Option((String) null, "h-R\"X>cr|H1p/YcDYGb");
      option0.setValueSeparator('m');
      char char0 = option0.getValueSeparator();
      assertEquals('m', char0);
  }

  @Test(timeout = 4000)
  public void test013()  throws Throwable  {
      Option option0 = new Option("value", "value");
      option0.getValue((String) null);
      assertEquals((-1), option0.getArgs());
      assertFalse(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test014()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.hasArg();
      option_Builder1.longOpt("*");
      Option option0 = option_Builder0.get();
      option0.processValue("37zj)w&'?jh:RxXL");
      String string0 = option0.getValue((int) '\u0000');
      assertFalse(option0.hasValueSeparator());
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test015()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.hasArg();
      option_Builder1.longOpt("*");
      Option option0 = option_Builder1.get();
      option0.processValue("37zj)w&'?jh:RxXL");
      String string0 = option0.getValue();
      assertNotNull(string0);
      assertFalse(option0.hasValueSeparator());
  }

  @Test(timeout = 4000)
  public void test016()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("value");
      option_Builder0.since("dKK");
      Option option0 = option_Builder0.get();
      option0.getSince();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test017()  throws Throwable  {
      Option option0 = new Option("IR", "IR");
      option0.getOpt();
      assertEquals((-1), option0.getArgs());
      assertFalse(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test018()  throws Throwable  {
      Option option0 = new Option("n", "");
      String string0 = option0.getLongOpt();
      assertEquals("", option0.getDescription());
      assertEquals((-1), option0.getArgs());
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test019()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.longOpt("");
      Option option0 = option_Builder0.get();
      option0.getLongOpt();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test020()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null, true, (String) null);
      String string0 = option0.getKey();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test021()  throws Throwable  {
      Option option0 = new Option("hH", ">tg?qT}G-).M`", false, "X*K");
      String string0 = option0.getDescription();
      assertEquals(">tg?qT}G-).M`", option0.getLongOpt());
      assertEquals((-1), option0.getArgs());
      assertEquals("X*K", string0);
  }

  @Test(timeout = 4000)
  public void test022()  throws Throwable  {
      Option option0 = new Option((String) null, "h-R\"X>cr|H1p/YcDYGb");
      option0.setDescription("");
      option0.getDescription();
      assertEquals((-1), option0.getArgs());
      assertFalse(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test023()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("1");
      Option.Builder option_Builder1 = option_Builder0.deprecated();
      Option option0 = option_Builder1.get();
      option0.getDeprecated();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test024()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("FF");
      option_Builder0.numberOfArgs(0);
      Option option0 = option_Builder0.get();
      int int0 = option0.getArgs();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test025()  throws Throwable  {
      Option option0 = new Option("Deprecated", "Deprecated", true, (String) null);
      int int0 = option0.getArgs();
      assertTrue(option0.hasLongOpt());
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test026()  throws Throwable  {
      Option option0 = new Option("value", "value");
      option0.setArgName("[ Option value[ARG...] :: value :: class java.lang.String ]");
      option0.getArgName();
      assertEquals((-1), option0.getArgs());
      assertFalse(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test027()  throws Throwable  {
      Option option0 = new Option("QzQn", "QzQn", false, "QzQn");
      option0.setArgName("");
      option0.getArgName();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test028()  throws Throwable  {
      Option option0 = new Option("0m0EkTx-p", "0m0EkTx-p");
      boolean boolean0 = option0.acceptsArg();
      assertFalse(boolean0);
      assertFalse(option0.hasLongOpt());
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test029()  throws Throwable  {
      Option option0 = new Option("82B", false, "82B");
      // Undeclared exception!
      try { 
        option0.setType((Object) "82B");
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // java.lang.String cannot be cast to java.lang.Class
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test030()  throws Throwable  {
      Option option0 = new Option("t", false, "t");
      option0.setArgs(45);
      // Undeclared exception!
      try { 
        option0.processValue((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // value
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test031()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.hasArg();
      Option.Builder option_Builder2 = option_Builder1.longOpt("a");
      Option option0 = option_Builder2.get();
      option0.processValue("37zj)w&'?jh:RxXL");
      try { 
        option0.getValue((-1));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test032()  throws Throwable  {
      Option option0 = new Option((String) null, true, "org.apache.commons.cli.DeprecatedAttributes");
      option0.setLongOpt("");
      // Undeclared exception!
      try { 
        option0.getId();
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test033()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null, true, (String) null);
      // Undeclared exception!
      try { 
        option0.getId();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test034()  throws Throwable  {
      // Undeclared exception!
      try { 
        Option.builder("$S&{<;61XMS;M/=@");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The option '$S&{<;61XMS;M/=@' contains an illegal character : '&'.
         //
         verifyException("org.apache.commons.cli.OptionValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test035()  throws Throwable  {
      Option option0 = null;
      try {
        option0 = new Option("Empty option name.", true, "Empty option name.");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The option 'Empty option name.' contains an illegal character : ' '.
         //
         verifyException("org.apache.commons.cli.OptionValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test036()  throws Throwable  {
      Option option0 = null;
      try {
        option0 = new Option("", "", true, "");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Empty option name.
         //
         verifyException("org.apache.commons.cli.OptionValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test037()  throws Throwable  {
      Option option0 = null;
      try {
        option0 = new Option("org.apache.commons.cli.Option$Builder", "?Ozwo");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The option 'org.apache.commons.cli.Option$Builder' contains an illegal character : '.'.
         //
         verifyException("org.apache.commons.cli.OptionValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test038()  throws Throwable  {
      Option option0 = new Option("hH", ">tg?qT}G-).M`", false, "X*K");
      option0.isDeprecated();
      assertEquals("X*K", option0.getDescription());
      assertEquals((-1), option0.getArgs());
      assertEquals(">tg?qT}G-).M`", option0.getLongOpt());
  }

  @Test(timeout = 4000)
  public void test039()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      DeprecatedAttributes deprecatedAttributes0 = DeprecatedAttributes.DEFAULT;
      Option.Builder option_Builder1 = option_Builder0.deprecated(deprecatedAttributes0);
      Option.Builder option_Builder2 = option_Builder1.longOpt(" ]");
      Option option0 = option_Builder2.get();
      boolean boolean0 = option0.isDeprecated();
      assertTrue(boolean0);
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test040()  throws Throwable  {
      Option option0 = new Option("hH", ">tg?qT}G-).M`", false, "X*K");
      boolean boolean0 = option0.hasValueSeparator();
      assertFalse(boolean0);
      assertEquals("X*K", option0.getDescription());
      assertEquals(">tg?qT}G-).M`", option0.getLongOpt());
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test041()  throws Throwable  {
      Option option0 = new Option((String) null, "h-R\"X>cr|H1p/YcDYGb");
      option0.setValueSeparator('m');
      boolean boolean0 = option0.hasValueSeparator();
      assertEquals('m', option0.getValueSeparator());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test042()  throws Throwable  {
      Option option0 = new Option("IR", "IR");
      boolean boolean0 = option0.hasArgs();
      assertFalse(boolean0);
      assertEquals((-1), option0.getArgs());
      assertFalse(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test043()  throws Throwable  {
      Option option0 = new Option((String) null, false, "/u%");
      option0.setArgs(157);
      boolean boolean0 = option0.hasArgs();
      assertEquals(157, option0.getArgs());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test044()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("value");
      option_Builder0.hasArgs();
      Option option0 = option_Builder0.get();
      boolean boolean0 = option0.hasArgs();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test045()  throws Throwable  {
      Option option0 = new Option("n", "");
      assertFalse(option0.hasArgs());
      
      option0.setArgs((-2));
      boolean boolean0 = option0.hasArg();
      assertEquals((-2), option0.getArgs());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test046()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null, true, (String) null);
      boolean boolean0 = option0.hasArg();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test047()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.longOpt("+-j<*U8%=,}B0");
      Option option0 = option_Builder0.get();
      boolean boolean0 = option0.hasArg();
      assertEquals((-1), option0.getArgs());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test048()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.longOpt("");
      Option option0 = option_Builder1.get();
      option0.getKey();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test049()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("NO_ARGS_ALLOWED");
      Option option0 = option_Builder0.get();
      option0.hasOptionalArg();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test050()  throws Throwable  {
      Option option0 = new Option("QzQn", "QzQn", false, "QzQn");
      Class<String> class0 = String.class;
      option0.setType(class0);
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test051()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder((String) null);
      Option.Builder option_Builder1 = option_Builder0.option((String) null);
      assertSame(option_Builder0, option_Builder1);
  }

  @Test(timeout = 4000)
  public void test052()  throws Throwable  {
      Option option0 = new Option((String) null, true, "org.apache.commons.cli.DeprecatedAttributes");
      String string0 = option0.toString();
      assertEquals("[ Option null [ARG] :: org.apache.commons.cli.DeprecatedAttributes :: class java.lang.String ]", string0);
  }

  @Test(timeout = 4000)
  public void test053()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      DeprecatedAttributes deprecatedAttributes0 = DeprecatedAttributes.DEFAULT;
      Option.Builder option_Builder1 = option_Builder0.deprecated(deprecatedAttributes0);
      Option.Builder option_Builder2 = option_Builder1.longOpt(" ]");
      Option option0 = option_Builder2.get();
      String string0 = option0.toString();
      assertEquals("[ Option null  ] Deprecated :: null :: class java.lang.String ]", string0);
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test054()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("1");
      option_Builder0.deprecated();
      Option option0 = option_Builder0.get();
      String string0 = option0.toDeprecatedString();
      assertEquals("Option '1': Deprecated", string0);
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test055()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null, true, (String) null);
      String string0 = option0.toDeprecatedString();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test056()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.longOpt("*");
      option_Builder0.hasArgs();
      Option option0 = option_Builder0.get();
      option0.processValue("37zj)w&'?jh:RxXL");
      boolean boolean0 = option0.requiresArg();
      assertFalse(option0.hasValueSeparator());
      assertTrue(option0.hasArg());
      assertEquals((-2), option0.getArgs());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test057()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.longOpt("*");
      option_Builder0.hasArgs();
      Option option0 = option_Builder0.get();
      boolean boolean0 = option0.requiresArg();
      assertTrue(boolean0);
      assertEquals((-2), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test058()  throws Throwable  {
      Option option0 = new Option((String) null, true, "DF-|A8rh]ViC6K\"6K");
      option0.processValue("DF-|A8rh]ViC6K\"6K");
      option0.setValueSeparator('-');
      // Undeclared exception!
      try { 
        option0.processValue("DF-|A8rh]ViC6K\"6K");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cannot add value, list full.
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test059()  throws Throwable  {
      Option option0 = new Option((String) null, true, "DF-|A8rh]ViC6K\"6K");
      option0.setValueSeparator('-');
      option0.processValue("DF-|A8rh]ViC6K\"6K");
      assertEquals('-', option0.getValueSeparator());
  }

  @Test(timeout = 4000)
  public void test060()  throws Throwable  {
      Option option0 = new Option("t", false, "t");
      // Undeclared exception!
      try { 
        option0.processValue("");
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // NO_ARGS_ALLOWED
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test061()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      DeprecatedAttributes deprecatedAttributes0 = DeprecatedAttributes.DEFAULT;
      Option.Builder option_Builder1 = option_Builder0.deprecated(deprecatedAttributes0);
      Option.Builder option_Builder2 = option_Builder1.longOpt(" ]");
      Option option0 = option_Builder2.get();
      String string0 = option0.toDeprecatedString();
      assertEquals((-1), option0.getArgs());
      assertEquals("Option 'null'' ]': Deprecated", string0);
  }

  @Test(timeout = 4000)
  public void test062()  throws Throwable  {
      Option option0 = new Option("IR", "IR");
      assertFalse(option0.hasLongOpt());
      
      option0.setLongOpt("[ Option IR :: IR :: class java.lang.String ]");
      boolean boolean0 = option0.hasLongOpt();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test063()  throws Throwable  {
      Option option0 = new Option("IR", "IR");
      boolean boolean0 = option0.hasLongOpt();
      assertEquals((-1), option0.getArgs());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test064()  throws Throwable  {
      Option option0 = new Option("n", "");
      assertFalse(option0.hasArg());
      
      option0.setArgs((-2));
      option0.toString();
      assertEquals((-2), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test065()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      option0.setArgName("");
      boolean boolean0 = option0.hasArgName();
      assertFalse(boolean0);
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test066()  throws Throwable  {
      Option option0 = new Option("t", false, "t");
      boolean boolean0 = option0.hasArgName();
      assertFalse(boolean0);
      assertEquals((-1), option0.getArgs());
      assertFalse(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test067()  throws Throwable  {
      Option option0 = new Option("t", false, "t");
      String[] stringArray0 = option0.getValues();
      assertEquals((-1), option0.getArgs());
      assertFalse(option0.hasLongOpt());
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test068()  throws Throwable  {
      Option option0 = new Option((String) null, true, "DF-|A8rh]ViC6K\"6K");
      assertTrue(option0.hasArg());
      
      option0.processValue("DF-|A8rh]ViC6K\"6K");
      String[] stringArray0 = option0.getValues();
      assertNotNull(stringArray0);
      assertFalse(option0.hasLongOpt());
      assertFalse(option0.hasValueSeparator());
  }

  @Test(timeout = 4000)
  public void test069()  throws Throwable  {
      Option option0 = new Option("n", "");
      String string0 = option0.getValue("n");
      assertEquals("", option0.getDescription());
      assertNotNull(string0);
      assertEquals((-1), option0.getArgs());
      assertFalse(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test070()  throws Throwable  {
      Option option0 = new Option("t", false, "t");
      option0.getValue(45);
      assertFalse(option0.hasLongOpt());
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test071()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.hasArg();
      option_Builder1.longOpt("*");
      Option option0 = option_Builder0.get();
      option0.processValue("37zj)w&'?jh:RxXL");
      try { 
        option0.getValue(16);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 16, Size: 1
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test072()  throws Throwable  {
      Option option0 = new Option("t", false, "t");
      option0.getValue();
      assertEquals((-1), option0.getArgs());
      assertFalse(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test073()  throws Throwable  {
      Option option0 = new Option("t", false, "t");
      option0.setArgs(45);
      option0.processValue("");
      option0.getValue();
      assertEquals(45, option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test074()  throws Throwable  {
      Option option0 = new Option("t", false, "t");
      String string0 = option0.getKey();
      assertNotNull(string0);
      assertEquals((-1), option0.getArgs());
      assertFalse(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test075()  throws Throwable  {
      Option option0 = new Option("I", "I");
      Option option1 = new Option("I", "I");
      boolean boolean0 = option0.equals(option1);
      assertTrue(boolean0);
      assertEquals((-1), option1.getArgs());
      assertFalse(option1.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test076()  throws Throwable  {
      Option option0 = new Option("I", "I");
      Option option1 = new Option("I", "I", false, "I");
      boolean boolean0 = option0.equals(option1);
      assertFalse(boolean0);
      assertEquals((-1), option1.getArgs());
  }

  @Test(timeout = 4000)
  public void test077()  throws Throwable  {
      Option option0 = new Option("IR", "IR");
      Option.Builder option_Builder0 = Option.builder("converterMap");
      Option option1 = option_Builder0.get();
      boolean boolean0 = option0.equals(option1);
      assertEquals((-1), option0.getArgs());
      assertFalse(option0.hasLongOpt());
      assertFalse(boolean0);
      assertEquals((-1), option1.getArgs());
  }

  @Test(timeout = 4000)
  public void test078()  throws Throwable  {
      Option option0 = new Option("I", "I");
      boolean boolean0 = option0.equals(option0);
      assertTrue(boolean0);
      assertEquals((-1), option0.getArgs());
      assertFalse(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test079()  throws Throwable  {
      Option option0 = new Option((String) null, true, "DF-|A8rh]ViC6K\"6K");
      boolean boolean0 = option0.equals("DF-|A8rh]ViC6K\"6K");
      assertTrue(option0.hasArg());
      assertFalse(option0.hasLongOpt());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test080()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.hasArg();
      Option.Builder option_Builder2 = option_Builder1.longOpt(" ]");
      Option option0 = option_Builder2.get();
      assertTrue(option0.hasArg());
      
      option0.processValue("");
      String string0 = option0.getValue("Q*zba})[M");
      assertFalse(option0.hasValueSeparator());
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test081()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder((String) null);
      Option.Builder option_Builder1 = option_Builder0.hasArgs();
      Option.Builder option_Builder2 = option_Builder0.optionalArg(true);
      assertSame(option_Builder2, option_Builder1);
  }

  @Test(timeout = 4000)
  public void test082()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder((String) null);
      Option.Builder option_Builder1 = option_Builder0.optionalArg(true);
      assertSame(option_Builder0, option_Builder1);
  }

  @Test(timeout = 4000)
  public void test083()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.optionalArg(false);
      assertSame(option_Builder1, option_Builder0);
  }

  @Test(timeout = 4000)
  public void test084()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder((String) null);
      Option.Builder option_Builder1 = option_Builder0.hasArg(false);
      assertSame(option_Builder0, option_Builder1);
  }

  @Test(timeout = 4000)
  public void test085()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.longOpt(" ]");
      Option option0 = option_Builder1.get();
      option0.getOpt();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test086()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.longOpt("*");
      Option option0 = option_Builder0.get();
      option0.getType();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test087()  throws Throwable  {
      Option option0 = new Option("IR", "IR");
      // Undeclared exception!
      try { 
        option0.addValue("converterMap");
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // The addValue method is not intended for client use. Subclasses should use the processValue method instead.
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test088()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.longOpt("*");
      Option option0 = option_Builder0.get();
      option0.getLongOpt();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test089()  throws Throwable  {
      Option option0 = new Option("t", false, "t");
      option0.hashCode();
      assertEquals((-1), option0.getArgs());
      assertFalse(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test090()  throws Throwable  {
      Option option0 = new Option((String) null, true, "DF-|A8rh]ViC6K\"6K");
      option0.isRequired();
      assertFalse(option0.hasLongOpt());
      assertTrue(option0.hasArg());
  }

  @Test(timeout = 4000)
  public void test091()  throws Throwable  {
      Option option0 = new Option("n", "");
      option0.getSince();
      assertEquals((-1), option0.getArgs());
      assertFalse(option0.hasLongOpt());
      assertEquals("", option0.getDescription());
  }

  @Test(timeout = 4000)
  public void test092()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      option0.getDescription();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test093()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      int int0 = option0.getArgs();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test094()  throws Throwable  {
      Option option0 = new Option("IR", "IR");
      option0.clearValues();
      assertEquals((-1), option0.getArgs());
      assertFalse(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test095()  throws Throwable  {
      Option option0 = new Option((String) null, true, "DF-|A8rh]ViC6K\"6K");
      option0.getDeprecated();
      assertEquals(1, option0.getArgs());
      assertFalse(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test096()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.longOpt("*");
      Option option0 = option_Builder1.get();
      option0.getValueSeparator();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test097()  throws Throwable  {
      Option option0 = new Option((String) null, "*");
      boolean boolean0 = option0.requiresArg();
      assertEquals((-1), option0.getArgs());
      assertFalse(option0.hasLongOpt());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test098()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      option0.setArgName("R");
      boolean boolean0 = option0.hasArgName();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test099()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.longOpt("*");
      Option option0 = option_Builder0.get();
      Option option1 = (Option)option0.clone();
      assertNotSame(option1, option0);
      assertEquals((-1), option1.getArgs());
  }

  @Test(timeout = 4000)
  public void test100()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.longOpt(" ]");
      Option option0 = option_Builder1.get();
      int int0 = option0.getId();
      assertEquals(32, int0);
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test101()  throws Throwable  {
      Option option0 = new Option("t", false, "t");
      Converter<?, ?> converter0 = option0.getConverter();
      option0.setConverter(converter0);
      Converter<?, ?> converter1 = option0.getConverter();
      assertFalse(option0.hasLongOpt());
      assertEquals((-1), option0.getArgs());
      assertNotNull(converter1);
  }

  @Test(timeout = 4000)
  public void test102()  throws Throwable  {
      Option option0 = new Option("n", "");
      option0.getValuesList();
      assertEquals("", option0.getDescription());
      assertFalse(option0.hasLongOpt());
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test103()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.longOpt("*");
      Option option0 = option_Builder0.get();
      option0.setRequired(true);
      assertTrue(option0.isRequired());
  }

  @Test(timeout = 4000)
  public void test104()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.longOpt("*");
      Option option0 = option_Builder0.get();
      option0.setOptionalArg(true);
      boolean boolean0 = option0.requiresArg();
      assertTrue(option0.hasOptionalArg());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test105()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.longOpt("*");
      Option option0 = option_Builder0.get();
      option0.getArgName();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test106()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      option0.setType((Object) null);
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test107()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder((String) null);
      Class<Object> class0 = Object.class;
      Option.Builder option_Builder1 = option_Builder0.type(class0);
      assertSame(option_Builder0, option_Builder1);
  }

  @Test(timeout = 4000)
  public void test108()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.desc("");
      assertSame(option_Builder0, option_Builder1);
  }

  @Test(timeout = 4000)
  public void test109()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      Converter<?, ?> converter0 = option0.getConverter();
      assertNotNull(converter0);
      
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.converter(converter0);
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test110()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder((String) null);
      Option.Builder option_Builder1 = option_Builder0.argName((String) null);
      assertSame(option_Builder1, option_Builder0);
  }

  @Test(timeout = 4000)
  public void test111()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      // Undeclared exception!
      try { 
        option_Builder0.get();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Either opt or longOpt must be specified
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test112()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder((String) null);
      Option.Builder option_Builder1 = option_Builder0.valueSeparator();
      assertSame(option_Builder1, option_Builder0);
  }
}
