/*
 * This file was automatically generated by EvoSuite
 * Sat Nov 15 01:22:38 GMT 2025
 */

package org.apache.commons.cli;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.sql.SQLClientInfoException;
import java.sql.SQLSyntaxErrorException;
import java.sql.SQLTransientConnectionException;
import java.sql.SQLWarning;
import org.apache.commons.cli.ParseException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ParseException_ESTest extends ParseException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SQLTransientConnectionException sQLTransientConnectionException0 = new SQLTransientConnectionException();
      ParseException parseException0 = new ParseException(sQLTransientConnectionException0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SQLClientInfoException sQLClientInfoException0 = new SQLClientInfoException();
      SQLSyntaxErrorException sQLSyntaxErrorException0 = new SQLSyntaxErrorException("", "*D_U_3)^pM", 0, sQLClientInfoException0);
      UnsupportedOperationException unsupportedOperationException0 = new UnsupportedOperationException(sQLSyntaxErrorException0);
      try { 
        ParseException.wrap(unsupportedOperationException0);
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ParseException parseException0 = new ParseException("");
      ParseException parseException1 = ParseException.wrap(parseException0);
      assertSame(parseException0, parseException1);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      SQLWarning sQLWarning0 = new SQLWarning();
      ParseException parseException0 = ParseException.wrap(sQLWarning0);
      assertNotNull(parseException0);
  }
}
