/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Sat Nov 15 01:16:32 GMT 2025
 */

package org.apache.commons.cli;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class GnuParser_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.apache.commons.cli.GnuParser"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "Cp1252"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "C:\\Users\\jakub\\AppData\\Local\\Temp\\"); 
    java.lang.System.setProperty("user.country", "US"); 
    java.lang.System.setProperty("user.dir", "C:\\Users\\jakub\\OneDrive\\Documents\\SCHOOL\\assignment2"); 
    java.lang.System.setProperty("user.home", "C:\\Users\\jakub"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "jakub"); 
    java.lang.System.setProperty("user.timezone", "America/New_York"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(GnuParser_ESTest_scaffolding.class.getClassLoader() ,
      "org.apache.commons.io.filefilter.IOFileFilter",
      "org.apache.commons.lang3.mutable.MutableInt",
      "org.apache.commons.cli.DefaultParser$NonOptionAction",
      "org.apache.commons.text.similarity.SimilarityCharacterInput",
      "org.apache.commons.cli.DefaultParser$Builder",
      "org.apache.commons.lang3.StringUtils",
      "org.apache.commons.cli.DefaultParser",
      "org.apache.commons.text.matcher.StringMatcherFactory",
      "org.apache.commons.cli.Converter",
      "org.apache.commons.cli.AmbiguousOptionException",
      "org.apache.commons.cli.DeprecatedAttributes",
      "org.apache.commons.cli.UnrecognizedOptionException",
      "org.apache.commons.text.matcher.AbstractStringMatcher",
      "org.apache.commons.text.TextStringBuilder",
      "org.apache.commons.cli.Parser",
      "org.apache.commons.text.TextStringBuilder$TextStringBuilderTokenizer",
      "org.apache.commons.text.similarity.EditDistance",
      "org.apache.commons.text.similarity.LongestCommonSubsequenceDistance",
      "org.apache.commons.cli.ParseException",
      "org.apache.commons.text.similarity.LongestCommonSubsequence",
      "org.apache.commons.lang3.mutable.Mutable",
      "org.apache.commons.text.similarity.SimilarityScore",
      "org.apache.commons.text.similarity.ObjectSimilarityScore",
      "org.apache.commons.io.file.PathFilter",
      "org.apache.commons.cli.Util",
      "org.apache.commons.text.Builder",
      "org.apache.commons.text.similarity.HammingDistance",
      "org.apache.commons.text.TextStringBuilder$TextStringBuilderReader",
      "org.apache.commons.cli.Options",
      "org.apache.commons.cli.DeprecatedAttributes$Builder",
      "org.apache.commons.lang3.ArrayUtils",
      "org.apache.commons.text.matcher.AbstractStringMatcher$CharSetMatcher",
      "org.apache.commons.text.matcher.AbstractStringMatcher$NoneMatcher",
      "org.apache.commons.text.matcher.AbstractStringMatcher$CharMatcher",
      "org.apache.commons.text.TextStringBuilder$TextStringBuilderWriter",
      "org.apache.commons.cli.GnuParser",
      "org.apache.commons.cli.OptionValidator",
      "org.apache.commons.cli.CommandLine",
      "org.apache.commons.cli.Option",
      "org.apache.commons.text.matcher.AbstractStringMatcher$CharArrayMatcher",
      "org.apache.commons.cli.CommandLineParser",
      "org.apache.commons.text.StringTokenizer",
      "org.apache.commons.cli.Option$Builder",
      "org.apache.commons.text.similarity.SimilarityInput",
      "org.apache.commons.cli.MissingOptionException",
      "org.apache.commons.text.matcher.StringMatcher",
      "org.apache.commons.text.matcher.AbstractStringMatcher$TrimMatcher",
      "org.apache.commons.cli.CommandLine$Builder",
      "org.apache.commons.lang3.function.FailableFunction",
      "org.apache.commons.cli.AlreadySelectedException",
      "org.apache.commons.cli.OptionGroup",
      "org.apache.commons.cli.MissingArgumentException"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(GnuParser_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.apache.commons.cli.Parser",
      "org.apache.commons.cli.GnuParser",
      "org.apache.commons.cli.Util",
      "org.apache.commons.cli.Options",
      "org.apache.commons.cli.Option",
      "org.apache.commons.cli.OptionValidator",
      "org.apache.commons.cli.OptionGroup",
      "org.apache.commons.cli.CommandLine",
      "org.apache.commons.cli.CommandLine$Builder",
      "org.apache.commons.cli.Option$Builder",
      "org.apache.commons.cli.DefaultParser",
      "org.apache.commons.cli.ParseException",
      "org.apache.commons.cli.MissingOptionException",
      "org.apache.commons.text.TextStringBuilder",
      "org.apache.commons.text.matcher.AbstractStringMatcher",
      "org.apache.commons.text.matcher.AbstractStringMatcher$CharMatcher",
      "org.apache.commons.text.matcher.AbstractStringMatcher$NoneMatcher",
      "org.apache.commons.text.matcher.AbstractStringMatcher$CharSetMatcher",
      "org.apache.commons.text.matcher.AbstractStringMatcher$TrimMatcher",
      "org.apache.commons.text.matcher.StringMatcherFactory",
      "org.apache.commons.text.StringTokenizer",
      "org.apache.commons.text.TextStringBuilder$TextStringBuilderTokenizer",
      "org.apache.commons.lang3.StringUtils",
      "org.apache.commons.cli.UnrecognizedOptionException",
      "org.apache.commons.lang3.ArrayUtils",
      "org.apache.commons.cli.MissingArgumentException",
      "org.apache.commons.io.filefilter.IOFileFilter",
      "org.apache.commons.cli.DeprecatedAttributes",
      "org.apache.commons.text.similarity.LongestCommonSubsequenceDistance",
      "org.apache.commons.text.similarity.LongestCommonSubsequence",
      "org.apache.commons.text.similarity.HammingDistance",
      "org.apache.commons.text.similarity.SimilarityCharacterInput"
    );
  }
}
