/*
 * This file was automatically generated by EvoSuite
 * Sat Nov 15 01:26:04 GMT 2025
 */

package org.apache.commons.cli.help;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.Stack;
import java.util.Vector;
import org.apache.commons.cli.Option;
import org.apache.commons.cli.example.WeirdOptionFormat;
import org.apache.commons.cli.help.TableDefinition;
import org.apache.commons.cli.help.TextStyle;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TableDefinition_ESTest extends TableDefinition_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Stack<TextStyle> stack0 = new Stack<TextStyle>();
      Stack<String> stack1 = new Stack<String>();
      TableDefinition tableDefinition0 = TableDefinition.from("&iO T/;XqY<+Y#g*", stack0, stack1, (Iterable<List<String>>) null);
      Iterable<List<String>> iterable0 = tableDefinition0.rows();
      assertNull(iterable0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ArrayList<TextStyle> arrayList0 = new ArrayList<TextStyle>();
      TableDefinition tableDefinition0 = TableDefinition.from("bn6EK", arrayList0, (List<String>) null, (Iterable<List<String>>) null);
      List<String> list0 = tableDefinition0.headers();
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      LinkedList<TextStyle> linkedList0 = new LinkedList<TextStyle>();
      ArrayList<String> arrayList0 = new ArrayList<String>();
      TableDefinition tableDefinition0 = TableDefinition.from("", linkedList0, arrayList0, (Iterable<List<String>>) null);
      List<String> list0 = tableDefinition0.headers();
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Stack<TextStyle> stack0 = new Stack<TextStyle>();
      Stack<String> stack1 = new Stack<String>();
      stack1.add("SimilarityInput must have the same length");
      TableDefinition tableDefinition0 = TableDefinition.from("&iO T/;XqY<+Y#g*", stack0, stack1, (Iterable<List<String>>) null);
      List<String> list0 = tableDefinition0.headers();
      assertTrue(list0.contains("SimilarityInput must have the same length"));
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Vector<String> vector0 = new Vector<String>();
      HashSet<List<String>> hashSet0 = new HashSet<List<String>>();
      ArrayList<List<String>> arrayList0 = new ArrayList<List<String>>(hashSet0);
      TableDefinition tableDefinition0 = TableDefinition.from("", (List<TextStyle>) null, vector0, arrayList0);
      List<TextStyle> list0 = tableDefinition0.columnTextStyles();
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Stack<TextStyle> stack0 = new Stack<TextStyle>();
      Stack<String> stack1 = new Stack<String>();
      TableDefinition tableDefinition0 = TableDefinition.from("&iO T/;XqY<+Y#g*", stack0, stack1, (Iterable<List<String>>) null);
      List<TextStyle> list0 = tableDefinition0.columnTextStyles();
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Stack<TextStyle> stack0 = new Stack<TextStyle>();
      ArrayList<String> arrayList0 = new ArrayList<String>();
      Stack<List<String>> stack1 = new Stack<List<String>>();
      HashSet<List<String>> hashSet0 = new HashSet<List<String>>(stack1);
      TableDefinition tableDefinition0 = TableDefinition.from((String) null, stack0, arrayList0, hashSet0);
      String string0 = tableDefinition0.caption();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Stack<TextStyle> stack0 = new Stack<TextStyle>();
      Stack<String> stack1 = new Stack<String>();
      TableDefinition tableDefinition0 = TableDefinition.from("&iO T/;XqY<+Y#g*", stack0, stack1, (Iterable<List<String>>) null);
      String string0 = tableDefinition0.caption();
      assertEquals("&iO T/;XqY<+Y#g*", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      Stack<Option> stack0 = new Stack<Option>();
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) stack0);
      Iterable<List<String>> iterable0 = tableDefinition0.rows();
      assertNotNull(iterable0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      Stack<Option> stack0 = new Stack<Option>();
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) stack0);
      String string0 = tableDefinition0.caption();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      Stack<Option> stack0 = new Stack<Option>();
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) stack0);
      List<TextStyle> list0 = tableDefinition0.columnTextStyles();
      assertFalse(list0.isEmpty());
  }
}
